url: https://etal.github.io  # the base hostname and protocol for your site, e.g. http://example.com
domain: etal.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Bio" # the name of your site, e.g. ACME Corp.
description: "Bioinformatics consultant"
theme: jekyll-theme-cayman
github_url: https://github.com/etal
linkedin_url: https://www.linkedin.com/in/etalevich/
bluesky_url: https://bsky.app/profile/etalevich.bsky.social
scholar_url: https://scholar.google.com/citations?user=kYZERHwAAAAJ
